name: inferno
channels:
- defaults
- soumith
dependencies:
- libgfortran=3.0.0=1
- mkl=2017.0.1=0
- numpy=1.12.1=py36_0
- openssl=1.0.2k=1
- pip=9.0.1=py36_1
- pyyaml=3.12=py36_0
- python=3.6.1=0
- readline=6.2=2
- scikit-learn=0.18.1=np112py36_1
- scipy=0.19.0=np112py36_0
- setuptools=27.2.0=py36_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- pytorch=0.1.12=py361_2cu80
- wheel=0.29.0=py36_0
- xz=5.2.2=1
- yaml=0.1.6=0
- zlib=1.2.8=3
- pip:
  - tabulate==0.7.7